# Use the official Node.js image as the base
FROM node:14

# Set the working directory inside the container
WORKDIR /web

# Copy package.json and package-lock.json to the working directory
COPY library_front/package*.json ./

# Install the dependencies
RUN npm install

# Copy the application code to the working directory
COPY library_front .

# Expose the port on which the Node.js application will listen
EXPOSE 3000

# Define the command to start the Node.js application
CMD [ "npm", "start" ]
